### ISSUE TITLE
Kernel not recognizing ext2 partition correctly

### ISSUE THREAD

**Issue by AlexsanderDamaceno** [byteduck/duckOS#1]
hello i'm having the following problem when  i try to execute the duckos in qemu 

[kinit] Unsupported ext2 version 0.35585. Must be at least 1. Hanging.

**Comment by byteduck** [comment]
That's weird. What operating system are you on? Did you notice any errors when running the build scripts? Are you using the qemu scripts to run it?

**Comment by AlexsanderDamaceno** [comment]
i'm using ubuntu.tte  scripts is all right everthing compiled very well but when i execute the image then i get this error.

**Comment by byteduck** [comment]
Could you upload your image somewhere so I can examine it? It should be in the build folder.

**Comment by AlexsanderDamaceno** [comment]
yes , here it's the image : https://drive.google.com/file/d/10tUa-r1CoNBCpg7ac1zaOZ13dJgvJqZy/view?usp=sharing

**Comment by AlexsanderDamaceno** [comment]
i'm using a older commit so the image it's 50 mb

**Comment by AlexsanderDamaceno** [comment]
but with 100 mb i get the same error

**Comment by byteduck** [comment]
It definitely seems like there's some kind of issue reading the ext2 superblock. I'll look into this.

**Comment by byteduck** [comment]
Upon further inspection, this seems to only happen when running directly from your disk image when using `make qemu-image`. Try using `make qemu-kernel` for now. I'm not sure why this is happening, but I'll continue examining your disk image.

**Comment by AlexsanderDamaceno** [comment]
![Screenshot from 2021-06-04 17-28-25](https://user-images.githubusercontent.com/40966997/120859225-4927b680-c55a-11eb-8495-f69fa960e0c6.png)
this is what a get when a use make qemu-kernel

**Comment by AlexsanderDamaceno** [comment]
i get the following when executing with qemu-kernel 
![Screenshot from 2021-06-04 17-31-59](https://user-images.githubusercontent.com/40966997/120859593-ceab6680-c55a-11eb-887b-394436cbd66b.png)

**Comment by byteduck** [comment]
Upon further inspection, your image seems to be quite weird. It has a directory named `*` in the root, doesn't pass a filesystem check, and is missing some key files. Try starting from scratch again, and see if that works (ie cloning the repository again from the latest commit, rebuilding the toolchain, and then building the OS)

**Comment by AlexsanderDamaceno** [comment]
ok  i'll try , how can i message you private to know some things about the kernel ?

**Comment by byteduck** [comment]
Of course! I can also send you a copy of the image if you'd like, so you can play around with it in the meantime.

**Comment by AlexsanderDamaceno** [comment]
do you have discord ?

**Comment by byteduck** [comment]
I do, but I think email might be better to continue this conversation for now. You can reach me at duck@byteduck.dev

**Comment by AlexsanderDamaceno** [comment]
ok , i send some doubts

**Comment by AlexsanderDamaceno** [comment]
can you send the image ?

**Comment by byteduck** [comment]
I rebuilt it from scratch on my end and I'm getting the same error, so it's definitely not your end.

**Comment by AlexsanderDamaceno** [comment]
maybe some wrong flag in image.sh

**Comment by byteduck** [comment]
This has been fixed in 1a63d8bbf39a49349727cb98875a8d61753cc1df. The issue was that throughout the kernel, there are ASSERT() statements which will cause the kernel to red-screen if the enclosed statement evaluates to false. If the DEBUG flag is not defined, however (as it isn't by default), these ASSERTs are disabled, and thus the conditions within them were not evaluated. I had a few important lines of code wrapped within ASSERTs, meaning they weren't run if the kernel was compiled without the DEBUG flag. This included important things such as yielding while waiting for an interrupt during a DMA disk transfer. Now, the ASSERTs will simply print a warning to the kernel log if they evaluate to false in non-debug mode, and thus their conditions are always evaluated, fixing this issue.
