### ISSUE TITLE
[SUGGESTION] “duckfetch”

### ISSUE THREAD

**Issue by PF94** [byteduck/duckOS#16]
# Suggestion

duckOS should have an application that works similarly to Neofetch (which is unfortunately bash-based). This might need code to figure out what GPU/CPU is installed along with the motherboard’s name. Heck, maybe there should be a fancy ASCII logo to the left of the information.

**Comment by byteduck** [comment]
This would be fun! The kernel doesn't currently expose a lot of the information you'd probably want to see in this, but there is some stuff exposed (like memory info) with procFS. `libsys` exposes this stuff with a nice wrapper so you don't have to parse it yourself. If you want to write something like this and submit a PR, that would be fun!

**Comment by byteduck** [comment]
Closing for now, feel free to submit a PR.
