### ISSUE TITLE
[BUG] DOOM port no longer works

### ISSUE THREAD

**Issue by PF94** [byteduck/duckOS#18]
## Information

Opening the Doom port causes the system to no longer be responsive.

## Logs

If applicable, insert relevant log contents here.

```
pond(3) [INFO] New client connected: 55c3692b
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
pond(3) [ERROR] [River] Error writing packet: No space left on device
```

## Screenshot

![image](https://user-images.githubusercontent.com/45898787/193864836-b28a0ce5-5b07-4aba-b1e0-0335efe1c200.png)

## Environment

Describe what you were doing when the crash or bug occurred. Additionally, provide information about the environment (if you aren't sure, don't worry if you need to leave something blank):
- *Host Operating System or Machine*: Ubuntu 20.04 (KDE Neon, ironic because I switched to Trinity)
- *QEMU or Virtualization Software Version*: 7.1.0

## To Reproduce

Steps to reproduce the bug, if possible:
1. Boot
2. Open Doom

**Comment by byteduck** [comment]
Do you have DOOM1.wad (or another supported WAD file) installed to `/apps/doom.app`? (You can add user-defined files to the image via the `user` folder in the root of the repository as per the README. Otherwise, DOOM won't load.

Obviously, it shouldn't freeze up the whole thing regardless. It's because pond isn't able to write packets to the app since it becomes unresponsive, but it should just be throwing those away instead of waiting until it can. I'll look into it.

**Comment by PF94** [comment]
yeah it turns out i forgot to install the shareware wad.

![image](https://user-images.githubusercontent.com/45898787/193889112-aae72ee3-a4fb-4b17-bd87-0c19ecda1407.png)

**Comment by byteduck** [comment]
Just to confirm, when you launched it without the WAD, did the whole system become unresponsive? i.e. unable to move the mouse pointer or open other apps? (opening apps does break sometimes due to the broken map implementation, which is unrelated 🙃)

**Comment by PF94** [comment]
the mouse pointer did move but more and more packet errors showed up when i did.

**Comment by byteduck** [comment]
Oh, okay. That's expected then - that's essentially just Pond complaining that DOOM isn't reading the packets it's sending.
