### ISSUE TITLE
How to start pond?

### ISSUE THREAD

**Issue by ajh123** [byteduck/duckOS#2]
When I do a full clean build, QEMU greets me with a black screen that I can type in and that's it. How to start pond?

**Comment by ajh123** [comment]
@byteduck my qemu log output looks like this
```
$ make qemu
qemu-system-x86_64: --display help: Invalid parameter 'help'
qemu-system-x86_64: --display help: Invalid parameter 'help'
qemu-system-x86_64: multiboot knows VBE. we don't
[kinit] [INFO] Starting duckOS...
[CommandLine] [INFO] Command line options: 'kernel/duckk32 ""'
[VGA] [INFO] Found a bochs-compatible VGA device at 0:2.0
[PATA] [INFO] Setup disk QEMU HARDDISK using DMA (270880 blocks)
```

**Comment by MarcoCicognani** [comment]
I noticed the same behavior on QEMU for LinuxMint 20.2.
On Ubuntu 21.10 it works fine...

**Comment by ajh123** [comment]
Thanks, I will try to update my Ubuntu 20.0.4 (I think?) to the latest later, when I'm home again

**Comment by ajh123** [comment]
Things have improved but the mouse does not seem to work :(

**Comment by byteduck** [comment]
It seems like this is probably an issue with the QEMU script not working properly with older versions of QEMU. What happens if you use the command `qemu-system-x86_64 -s -kernel kernel/duckk32 -append "" -drive file=$DUCKOS_IMAGE,cache=directsync,format=raw,id=disk,if=ide -m 512M -serial stdio -enable-kvm` from within your `cmake-build` directory?

**Comment by ajh123** [comment]
```Block format 'raw' does not support the option 'guess'``` shows in qemu log

**Comment by ajh123** [comment]
then it quits

**Comment by ajh123** [comment]
And without ```guess``` qemu logs 
```
Could not access KVM kernel module: No such file or directory
qemu-system-x86_64: failed to initialize kvm: No such file or directory
```

**Comment by ajh123** [comment]
And without KMM it works!

**Comment by PF94** [comment]
> And without KMM it works!

does not work for me.
