### ISSUE TITLE
[SUGGESTION] Missing UI elements

### ISSUE THREAD

**Issue by PF94** [byteduck/duckOS#21]
# Suggestion

* Proper menus
* Text bar/box
* Toolbars(?)
* Dialogs
* Tabs

**Comment by byteduck** [comment]
Great ideas! I've been wanting to add more UI elements like these, but it's been taking a backseat to stuff behind the scenes like stability.

**Comment by PF94** [comment]
tbh i might be looking too far ahead

**Comment by ajh123** [comment]
Maybe Nuklear or ImGui could be added? They are complete very lightweight and portable GUI libraries. People have even got ImGui to run an an Ardunio! They contain menu bars, windows, buttons, graphs and much more!

**Comment by byteduck** [comment]
> Maybe Nuklear or ImGui could be added? They are complete very lightweight and portable GUI libraries. People have even got ImGui to run an an Ardunio! They contain menu bars, windows, buttons, graphs and much more!

The goal for now is to try and write everything from the ground up - duckOS isn't meant to be a usable or practical system at the moment, but more of a "just for fun" thing. I'm always open to ports if anyone wants to submit a PR though!

**Comment by byteduck** [comment]
Closing for now.
