### ISSUE TITLE
[SUGGESTION] About dialogs for applications

### ISSUE THREAD

**Issue by PF94** [byteduck/duckOS#23]
# Suggestion

What if applications had their own about dialog? Maybe that could be some form of "API".

**Comment by byteduck** [comment]
Good idea, I was thinking about this. Once we have a menu / keyboard shortcut system for opening them of course :>

**Comment by ajh123** [comment]
Maybe other dialogs. Like Yes/No, Open file, save (as) file, ..

**Comment by byteduck** [comment]
Closing for now - these things will be added on an as-needed basis.
