### ISSUE TITLE
[SUGGESTION] Web browser?

### ISSUE THREAD

**Issue by PF94** [byteduck/duckOS#29]
# Suggestion

I know it's a bit too early due to a lack of networking, but maybe a primitive web browser that opens local HTML files could be possible? It doesn't have to be fancy for now, just supporting HTML2.

**Comment by byteduck** [comment]
Well, parsing XML would be a good start, at least. This is pretty far out most likely, so I'll close it for now.

As an aside, maybe there's a better way to track suggestions than using issues. I'll look into something.
