### ISSUE TITLE
[make image] Cannot mount /dev/loop0p1 on Arch

### ISSUE THREAD

**Issue by PF94** [byteduck/duckOS#30]
I ditched Ubuntu 20.04 in favor of Arch due to problems with installing Wine and now I can't make the image file for duckOS via ``make image``. Searching everywhere yields irrelevant results regarding things like Ubuntu installation and partitioning. I know this is not the right place but I am not comfortable with trying to ask this on the Arch forums.

```
[INFO] Using existing image...
[INFO] Making loopback device...
[INFO] Loopback device mounted at /dev/loop0
[INFO] Mounting filesystem on /dev/loop0p1 to mnt ...
mount: /home/grkb/duckOS/cmake-build/mnt: special device /dev/loop0p1 does not exist.
       dmesg(1) may have more information after failed mount system call.
[ERROR] Couldn't mount.
[INFO] Cleaning up...
make[3]: *** [CMakeFiles/image.dir/build.make:70: CMakeFiles/image] Error 1
make[2]: *** [CMakeFiles/Makefile2:695: CMakeFiles/image.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:702: CMakeFiles/image.dir/rule] Error 2
make: *** [Makefile:169: image] Error 2
[grkb@archlinux cmake-build]$                                                                                
```

Fdisk claims that this is an "Inappropriate ioctl for device", which I can't find any fixes for on Google that isn't related to Perl/Bash scripts.

**Comment by PF94** [comment]
it now works but qemu doesn't show up at all?

**Comment by byteduck** [comment]
Anything interesting in the console? Is it running, or does it exit immediately? Can you run qemu-system-x86_64 directly in the terminal (with no arguments)?

**Comment by PF94** [comment]
> Anything interesting in the console? Is it running, or does it exit immediately? Can you run qemu-system-x86_64 directly in the terminal (with no arguments)?

it does run and it doesn't freeze at the hard drive part (unlike #11)

**Comment by byteduck** [comment]
Interesting. I am on arch , and I just upgraded qemu and it stopped working for me as well :thinking:

**Comment by byteduck** [comment]
For me at least, the issue was that it was booting, but Pond wasn't setting up the display correctly. This turned out to be due to the `gettimeofday` syscall in the kernel being implemented with `timespec` instead of `timeval`, which didn't decide to cause issues until now for some reason.

**Comment by PF94** [comment]
well for me the issue is that qemu's display is outputting as a VNC.

![image](https://user-images.githubusercontent.com/45898787/195138229-c5286f30-87a4-4252-8e15-7153aab82bef.png)
![image](https://user-images.githubusercontent.com/45898787/195138060-9f27f212-de15-427c-bc78-ca638d9944ea.png)

**Comment by PF94** [comment]
the vnc output issue is fixed by installing [qemu-ui-gtk](https://archlinux.org/packages/extra/x86_64/qemu-ui-gtk/).
