### ISSUE TITLE
[BUG] GCC port compiles, but does not run

### ISSUE THREAD

**Issue by byteduck** [byteduck/duckOS#32]
## Information

The GCC port compiles, but does not run. Instead, it segfaults before giving any output.

I believe this is due to some missing stack unwinding-related symbols that GCC expects from libgcc, which aren't included for some reason. So, the PLT entries resolve to 0x0 resulting in a segfault (I think).

**Comment by byteduck** [comment]
Update: The GCC port now runs! The issue turned out to be an incorrect implementation of `strncmp`, among some other things. However, `cc1` segfaults, even when just running `cpp`.

At least we can now print out the GCC version though!

**Comment by byteduck** [comment]
Another update: It runs even more now! For some reason, it complains about not being able to find `cc1` when running it with just `gcc`, but using the whole path and running `/usr/local/bin/gcc` works just fine :shrug:

Anyway, it gets all the way to linking now - but complains about `libgcc.a` being in the wrong format.

**Comment by ajh123** [comment]
Eventually we will be able to build the OS on the OS!

**Comment by byteduck** [comment]
Turns out it was due to a missing implementation of qsort in libc, among a few other things... GCC runs and compiles C programs properly now!
