### ISSUE TITLE
[SUGGESTION] User accounts

### ISSUE THREAD

**Issue by ajh123** [byteduck/duckOS#37]
# User Accounts

Instead of having just the "root" user why not allow us to have many different users. These would work in the same way as they do in Linux / Unix (halve way there already as there are "uids"). There would be a graphical and CLI ways for creating, deleting, ... operations on users.

In the future should there be Active Directory login?

Maybe there could be different authentication modules which could be created dynamically (like PAM in Linux)?

**Comment by byteduck** [comment]
User accounts are definitely on the roadmap. The basic infrastructure for users and permissions is mostly in place in the kernel already, with just a few more things needed to make it fully functional.

AD and PAM are probably out of scope for the time being, but could be revisited in the future.

**Comment by ajh123** [comment]
Maybe active directory support could be done in a more business orientated version. Maybe my fork ([GTMOS](https://github.com/ajh123-development/gtmos)) could become that? But when we have networking of course!

**Comment by byteduck** [comment]
Closing for now - the kernel has infrastructure for users, it's just not exposed in userspace in any meaningful way yet.
