### ISSUE TITLE
[BUG] Window resize issue

### ISSUE THREAD

**Issue by pawlos** [byteduck/duckOS#49]
## Information

When window is resized to possible minimum (1x1?) it's difficult and a bit unintuitive to resize it back.

## Logs

N/A

## Screenshot

N/A

## Environment

- WSL2/Win10
- Qemu 7.0.0

## To Reproduce

1. Open Calculator
2. Resize to minimal possible size -> window is almost invisible
3. Try to resize back (resizing in down-right direction)
4. This is not possible and window (still being small) is moved instead

## Additional context

The problem is that in such small window rect, the code that detect resize [direction](https://github.com/byteduck/duckOS/blob/master/services/pond/Display.cpp#L507) will evaluate always to `NORTHWEST` (the first possible value. This plus the fact that the cursor for `NORTHWEST` and `SOUTHEAST` looks the same, it's confusing that the only allowed resize direction is `NORTHWEST` and if user will try to resize down-right direction (`SOUTHEAST`), the window is moved instead of resizing (still being super hard to see).

The possible solution would be to limit the minimal window rectangle to `WINDOW_RESIZE_BORDER*2` to allow some room for determining which direction the resize will go. Other would be in such limited window size, determine the direction based on the mouse movement and not the position of the mouse in relation to the window's border.

**Comment by byteduck** [comment]
Minimum window size is another one of those things I need to implement and haven't gotten around to 🙂 we'd just need to add another IPC call for Pond for setting the minimum window size, and then libui could determine what the minimum window size should be based on the minimum preferred size of the root widget.

**Comment by pawlos** [comment]
Ok, that's also a valid way to go. I'll see if I can do something in that area.

**Comment by byteduck** [comment]
> Ok, that's also a valid way to go. I'll see if I can do something in that area.

I think limiting the minimum size to `WINDOW_RESIZE_BORDER*2` by default is also good, just in case windows don't set a minimum size or use libui.

**Comment by pawlos** [comment]
ok, I would like now to add simple Minesweeper to DuckOS so I'll get to this topic once that done.

**Comment by byteduck** [comment]
No rush! I'll probably do it :)

**Comment by byteduck** [comment]
Fixed! The windows must now have a minimum dimension of `WINDOW_RESIZE_BORDER*2` and can also set their minimum size explicitly. There's still a couple kinks in libui to deal with, in terms of the minimum size logic for widgets, but the root issue is fixed :)
