### ISSUE TITLE
[BUG] Problem with keyboard support

### ISSUE THREAD

**Issue by pawlos** [byteduck/duckOS#53]
## Information

I've noticed that at the time the app starts the keyboard events are not passed to the application. It requires to click on the app (I guess to give it a "focus") and only then the key events are being delivered.

## Logs

N/A

## Screenshot

N/A

## Environment

- Win10/WSL2
- Qemu 7.0.0

## To Reproduce

1. Open Terminal
2. Type ls -> nothing appears, cursor is blinking
3. Click on the terminal window
4. Type ls again - now, the letters appear

## Additional context
N/A

**Comment by byteduck** [comment]
This is sort of expected behavior, as opening windows isn't supposed to focus them. However, it would make sense to automatically focus new windows, as that is what users typically expect.

A simple fix would be to focus the window in libui when showing it as the default behavior.

**Comment by pawlos** [comment]
I was thinking it might be the case but the cursor was blinking, that gave me the indication that it was expecting an input.

**Comment by byteduck** [comment]
Ah, that makes sense. I suppose we shouldn't blink the cursor if the window is unfocused.

Additionally, I think maybe there needs to be some sort of visual indication of which window is focused - like dimming the title bar of those that are unfocused.

**Comment by byteduck** [comment]
Libui will now focus windows the first time they're shown, and it will also dim the title bar text when the window is unfocused. Additionally, terminal will stop blinking the cursor when the window is unfocused.
