### ISSUE TITLE
[Ports] Can't use configure in a git cloned repository?

### ISSUE THREAD

**Issue by PF94** [byteduck/duckOS#62]
![image](https://github.com/byteduck/duckOS/assets/45898787/d2827967-65cb-42e8-bc31-8c32f01d5318)
![image](https://github.com/byteduck/duckOS/assets/45898787/42573ba0-48b3-494b-a341-090ecea56c2e)

I'm assuming it's trying to look for ``[duckos trunk]/ports/build/bash/bash/configure``, since i could get configure working if i instead specified ``https://ftp.gnu.org/gnu/bash/bash-5.2.15.tar.gz``. However, I'm trying to use a git repository for this potential bash port instead of a tarball because I'm not experienced in patch files.

 ``export DOWNLOAD_FILE="../bash"`` seems to fix the problem, but it feels hacky.

**Comment by byteduck** [comment]
Weird question - if you remove the `ports/build/bash` directory and try again, does it work? It should be cloning directly there and not into `ports/build/bash/bash`, but if the folder is already there it may do that.

**Comment by PF94** [comment]
it is cloning into ``ports/build/bash``, without ``ports/build/bash/bash`` existing. adding ``export DOWNLOAD_FILE="../bash"`` fixes the issue, but it feels hacky.

![image](https://github.com/byteduck/duckOS/assets/45898787/bef79ca4-9f81-4700-a7ad-415deab28427)
(modified bash a little bit, it builds until plural.c due to this "plural.h" file that doesn't exist at all)

**Comment by byteduck** [comment]
I've added the ability to specify the path for the configure script, so you should be able to fix this by using `export CONFIGURE_PATH="./configure"` now.
