### ISSUE TITLE
[SUGGESTION]  Port system

### ISSUE THREAD

**Issue by turbocat2001** [byteduck/duckOS#67]
# Suggestion

Hello. I discovered that you are using CMake. However, the port system uses sh scripts. Have you thought about using CMake with the convenient `ExternalProject` instead?

**Comment by byteduck** [comment]
I haven't looked into it - this could streamline things a bit perhaps.

I think the main reason I'm using shell scripts at the moment is for the flexibility - it can check for dependencies, perform pre-build steps like cloning and patching, and call external build systems.

CMake can do all this as well, but I suppose the friction is just lower with shell scripts. I can look into it to see if a transition to CMake would be worth it though.

**Comment by byteduck** [comment]
After further investigation, I think it's better to leave it as a separate build system; it gives us a bit more flexibility and we don't necessarily want a catch-all `make install` to build all the ports as well (it is technically possible to exclude them, but it's using a hack and isn't officially supported by CMake).
