### ISSUE TITLE
[SUGGESTION] WSL 1 Might not work

### ISSUE THREAD

**Issue by maxtyson123** [byteduck/duckOS#68]
# Suggestion

Ive noticed in your [docs](https://github.com/byteduck/duckOS/blob/master/INSTRUCTIONS.md) that you say using WSL 1 is an option, however the build [script](https://github.com/byteduck/duckOS/blob/master/scripts/image.sh) uses loop devices which is not supported in WSL 1 as far as I know

Had the same issue with my os, thought I would let you know.

**Comment by byteduck** [comment]
Good catch - I'll have to update the docs to reflect this.

**Comment by byteduck** [comment]
Fixed!
