### ISSUE TITLE
KStdLib: Class move constructors

### ISSUE THREAD

**Issue by MarcoCicognani** [byteduck/duckOS#7]
Hi man!
I really like your work, and It's a really nice source of inspiration for my project.

Anyway this is not an issue, instead a clarification request:
Why
`kstd::vector::vector(vector&&)`
`kstd::circular_queue::circular_queue(circular_queue&&)`
`kstd::queue::queue(queue&&)`
they allocate new memory (using `kcalloc()`) instead of simply perform a `[k]std::exchange()` of the internal fields?

This could improve performances and reduce OOM errors.

**Comment by byteduck** [comment]
Good catch - those container classes were developed in a hurry and I don't know why I did that.

**Comment by byteduck** [comment]
Fixed in commit 5b7837113a096f4ca32e27c5ab2f62c2b1dedb6a
