### ISSUE TITLE
An ISO please! 

### ISSUE THREAD

**Issue by rdwnsjjd** [byteduck/duckOS#8]
would you please put an ready ISO file in repository release section??

 maybe someone doesn't want/can to build it??

**Comment by byteduck** [comment]
Thank you for the suggestion! I'm working on figuring out a CI/CD solution (I believe that's the correct term?) to have nightly builds automatically published somewhere.

In the meantime, I actually have been toying with [v86](https://github.com/copy/v86), which uses WASM to run an emulated x86 CPU in the browser. I cooked up a quick demo that allows you to test duckOS in your browser a few days ago, and while it's not quite finished and ready (I was going to link it in the README), you can check it out [here](https://sonin.me/duckOS).

**Comment by byteduck** [comment]
I've looked into using GitHub actions for this sort of thing, and it doesn't look like this is really feasible without paying out-of-pocket for some kind of CD service. Realistically, the web-based v86 version is good enough for people who just want a quick demo, and anyone who wants to run it locally should be able to compile it themselves fairly easily if they want to.

Maybe this is something that could be revisited in the future, but for now I don't think it's a priority.
