### ISSUE TITLE
qemu execution error

### ISSUE THREAD

**Issue by pdpdds** [byteduck/duckOS#9]
i successed kernel build and made disk image.
but i can not execute kernel.

build enviornment : wsl2, ubuntu 20.04 LTS

i think qemu shell script have problem.
so i executed manually.

qemu-system-x86_64.exe -s kernel kernel/duckk32 -drive file=duckOS.img,cache=directsync,format=raw,id=disk,if=ide -m 512M -serial stdio

ERROR:/home/stefan/src/qemu/repo.or.cz/qemu/ar7/block.c:1323:bdrv_open_driver: assertion failed: (is_power_of_2(bs->bl.request_alignment))

can you suggest resolution?
thanks!!

**Comment by byteduck** [comment]
This sounds like it's a [bug in qemu](https://bugs.launchpad.net/qemu/+bug/1893807) - you will probably have to use a newer or older version of qemu to see if it fixes the issue.
